export const movies = [
    {id:1,
        title:"Lucifer",
     img:"https://image.tmdb.org/t/p/w500/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
     match:"85% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Crime, Sci-Fi & Fantasy"},
    {id:2,
        title:"BoJack Horseman",
     img:"https://image.tmdb.org/t/p/w500/6JFWzlChcGgLiIUo2COgNlWGFKy.jpg",
     match:"86% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Animation, Comedy, Drama"},
    {id:3,
        title:"The Crown",
     img:"https://image.tmdb.org/t/p/w500/tjUEdX1Pzn1VqNlpUduEnnhhRH4.jpg",
     match:"82% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Drama"},
    {id:4,
        title:"Star Wars: The Clone Wars",
     img:"https://image.tmdb.org/t/p/original/m6eRgkR1KC6Mr6gKx6gKCzSn6vD.jpg",
     match:"85% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Adventure, Animation, Sci-Fi & Fantasy"},
    {id:5,
        title:"Longmire",
     img:"https://image.tmdb.org/t/p/w500/yrdt5lscyJ5j5GSbhl99x3SRN66.jpg",
     match:"78% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Crime, Drama, Western"},
   
    {id:6,
        title:"Stranger Things",
     img:"https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
     match:"86% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Drama, Mystery, Sci-Fi & Fantasy"},
    {id:7,
        title:"The Witcher",
     img:"https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
     match:"86% Match",
    content:"Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    gener:"Drama, Mystery, Sci-Fi & Fantasy"},
   
]

